[versions]
agp = "8.9.3"
kotlin = "2.2.0"
compose-multiplatform = "1.9.0"
android-compose = "1.9.2"
compose-material3 = "1.4.0"
androidx-activityCompose = "1.11.0"
firebase-bom = "34.3.0"
google-play-services = "4.4.3"
firebase-crashlytics-plugin = "2.9.9"
firebase-crashlytics = "19.4.4"
kotlinStdlib = "2.2.0"
runner = "1.5.2"
core = "1.5.0"
junit = "1.3.0"
play-services-auth = "21.0.0"
gitlive-firebase = "1.10.4"
koin-bom = "3.5.3"
orbit = "10.0.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
android-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "android-compose" }
android-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "android-compose" }
android-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "android-compose" }
android-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "android-compose" }
android-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlyticsKtx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
firebase-gitlive-common = { module = "dev.gitlive:firebase-common", version.ref = "gitlive-firebase" }
firebase-gitlive-auth = { module = "dev.gitlive:firebase-auth", version.ref = "gitlive-firebase" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose"}
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbit" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
orbit-test = { module = "org.orbit-mvi:orbit-test", version.ref = "orbit" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }

[bundles]
android-compose = ["android-compose-foundation", "android-compose-material3", "android-compose-ui", "android-compose-ui-tooling", "android-compose-ui-tooling-preview", "androidx-activity-compose"]
orbit = ["orbit-core", "orbit-viewmodel", "orbit-test", "orbit-compose"]
koin = ["koin-core", "koin-compose"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-playServices = { id = "com.google.gms.google-services", version.ref = "google-play-services" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin"}
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
